#!/bin/bash

if [[ " $@ " =~ " COMMON " ]] || [[ " $@ " =~ " ALL " ]]; then
  echo "COMMON PACKAGES INSTALL"
  paru -Suy --noconfirm - < ./packages/common
fi

if [[ " $@ " =~ " DOCKER " ]] || [[ " $@ " =~ " ALL " ]]; then
  echo "DOCKER INSTALL"
  paru -Suy --noconfirm docker
  sudo groupadd docker
  sudo usermod -aG docker $USER
  newgrp docker
fi

if [[ " $@ " =~ " FISH " ]] || [[ " $@ " =~ " ALL " ]]; then
  paru -S fisher fish --noconfirm
  fisher install IlanCosman/tide@v6
  tide configure --auto --style=Classic --prompt_colors='True color' --classic_prompt_color=Darkest --show_time='24-hour format' --classic_prompt_separators=Angled --powerline_prompt_heads=Sharp --powerline_prompt_tails=Sharp --powerline_prompt_style='Two lines, character' --prompt_connection=Dotted --powerline_right_prompt_frame=No --prompt_connection_andor_frame_color=Darkest --prompt_spacing=Sparse --icons='Many icons' --transient=No
fi

if [[ " $@ " =~ " K8S " ]] || [[ " $@ " =~ " ALL " ]]; then
  echo "K8S INSTALL"
  sudo pacman -S kubectl helm
  (
  set -x; cd "$(mktemp -d)" &&
  OS="$(uname | tr '[:upper:]' '[:lower:]')" &&
  ARCH="$(uname -m | sed -e 's/x86_64/amd64/' -e 's/\(arm\)\(64\)\?.*/\1\2/' -e 's/aarch64$/arm64/')" &&
  KREW="krew-${OS}_${ARCH}" &&
  curl -fsSLO "https://github.com/kubernetes-sigs/krew/releases/latest/download/${KREW}.tar.gz" &&
  tar zxvf "${KREW}.tar.gz" &&
  ./"${KREW}" install krew
  )
  kubectl krew update
  kubectl krew install modify-secret
fi

if [[ " $@ " =~ " PYTHON " ]] || [[ " $@ " =~ " ALL " ]]; then
  echo "PYTHON+PYENV INSTALL"
  paru -Suy --noconfirm python python-pip
  curl https://pyenv.run | bash
fi


if [[ " $@ " =~ " NODE " ]] || [[ " $@ " =~ " ALL " ]]; then
  paru -Suy --noconfirm nodejs npm
fi

if [[ " $@ " =~ " TMUX " ]] || [[ " $@ " =~ " ALL " ]]; then
  echo "TMUX CONFIG"

  git clone https://github.com/tmux-plugins/tpm ~/.tmux/plugins/tpm

fi
if [[ " $@ " =~ " JETBRAINS " ]] || [[ " $@ " =~ " ALL " ]]; then
  echo "JETRBAINS TOOLBOX AND IDEAVIM"
  wget https://download.jetbrains.com/toolbox/jetbrains-toolbox-2.5.2.35332.tar.gz -P /tmp/
  tar -xzf /tmp/jetbrains-toolbox-2.5.2.35332.tar.gz -C /tmp
  mv /tmp/**/jetbrains-toolbox ~/Toolbox
  ~/Toolbox/jetbrains-toolbox
  stow -R ideavim
fi

if [[ " $@ " =~ " KDE " ]]; then
  echo "KONSAVE IMPORT"
  paru -Suy --noconfirm konsave
  konsave -i ./thinkpad-a.knsv
  konsave -a thinkpad-a
fi

if [[ " $@ " =~ " SWAY " ]]; then
  echo "SWAY SETUP"
  paru -Syu --noconfirm - < ./packages/sway

  stow -S sway waybar scripts tmux kickstart-nvim fuzzel mako
fi

if [[ " $@ " =~ " DEVOPS " ]] || [[ " $@ " =~ " ALL " ]]; then
  echo "DEVOPS SETUP"
  paru -Syu --noconfirm - < ./packages/devops

  stow -S k9s
fi

echo "DONE"
