#!/bin/bash

if [[ " $@ " =~ " COMMON " ]] || [[ " $@ " =~ " ALL " ]]; then
  echo "COMMON PACKAGES INSTALL"
  paru -Suy - < ./packages/common
fi

if [[ " $@ " =~ " DOCKER " ]] || [[ " $@ " =~ " ALL " ]]; then
  echo "DOCKER INSTALL"
  paru -Suy docker
  sudo groupadd docker
  sudo usermod -aG docker $USER
  newgrp docker
fi

if [[ " $@ " =~ " FISH " ]] || [[ " $@ " =~ " ALL " ]]; then
  paru -S fisher fish
  fish -c 'fisher update'
fi

if [[ " $@ " =~ " K8S " ]] || [[ " $@ " =~ " ALL " ]]; then
  echo "K8S INSTALL"
  sudo pacman -S kubectl helm
  (
  set -x; cd "$(mktemp -d)" &&
  OS="$(uname | tr '[:upper:]' '[:lower:]')" &&
  ARCH="$(uname -m | sed -e 's/x86_64/amd64/' -e 's/\(arm\)\(64\)\?.*/\1\2/' -e 's/aarch64$/arm64/')" &&
  KREW="krew-${OS}_${ARCH}" &&
  curl -fsSLO "https://github.com/kubernetes-sigs/krew/releases/latest/download/${KREW}.tar.gz" &&
  tar zxvf "${KREW}.tar.gz" &&
  ./"${KREW}" install krew
  )
  kubectl krew update
  kubectl krew install modify-secret
fi

if [[ " $@ " =~ " PYTHON " ]] || [[ " $@ " =~ " ALL " ]]; then
  echo "PYTHON+PYENV INSTALL"
  paru -Suy python python-pip
  curl https://pyenv.run | bash
fi

if [[ " $@ " =~ " NODE " ]] || [[ " $@ " =~ " ALL " ]]; then
  paru -Suy nodejs npm
fi

if [[ " $@ " =~ " TMUX " ]] || [[ " $@ " =~ " ALL " ]]; then
  echo "TMUX CONFIG"

  git clone https://github.com/tmux-plugins/tpm ~/.tmux/plugins/tpm

  stow -S tmux
fi

if [[ " $@ " =~ " KDE " ]]; then
  echo "KONSAVE IMPORT"
  paru -Suy konsave
  konsave -i ./thinkpad-a.knsv
  konsave -a thinkpad-a
fi

if [[ " $@ " =~ " SWAY " ]]; then
  echo "SWAY SETUP"
  paru -Syu - < ./packages/sway

  stow -S sway waybar scripts kickstart-nvim fuzzel mako
fi

if [[ " $@ " =~ " DEVOPS " ]] || [[ " $@ " =~ " ALL " ]]; then
  echo "DEVOPS SETUP"
  paru -Syu - < ./packages/devops

  stow -S k9s
fi

echo "DONE"
