#! /bin/sh

_bc() {
	bspc config "$@"
}

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d I II III IV V VI VII VIII IX X

_bc border_width         	2
_bc window_gap          	1
# _bc config top_padding 		0


_bc automatic_scheme 		spiral
_bc split_ratio         	0.50
_bc borderless_monocle   	true
_bc gapless_monocle      	true
_bc single_monocle 			true
_bc normal_border_color		"#000000"
_bc active_border_color	    "#000000"
_bc focused_border_color	"#CA642E"
_bc presel_feedback_color	"#CA642E"
_bc urgent_border_color 	"#CA642E"

# bspc rule -a Gimp desktop='^8' state=floating follow=on
# bspc rule -a Chromium desktop='^2'
# bspc rule -a mplayer2 state=floating
# bspc rule -a Kupfer.py focus=on
# bspc rule -a Screenkey manage=off


#              _            _             _   
#   __ _ _   _| |_ ___  ___| |_ __ _ _ __| |_ 
#  / _` | | | | __/ _ \/ __| __/ _` | '__| __|
# | (_| | |_| | || (_) \__ \ || (_| | |  | |_ 
#  \__,_|\__,_|\__\___/|___/\__\__,_|_|   \__|


nitrogen --restore
$HOME/.config/polybar/launch.sh
picom --config $HOME/.config/picom/picom.conf

