set -g mouse on     #For tmux version 2.1 and up

set-window-option -g mode-keys vi
# Start windows and panes at 1, not 0
set -g base-index 1
setw -g pane-base-index 1
set-option -g update-environment "PATH" 
set-option -g prefix C-b
bind-key C-b send-prefix

bind-key "t" run-shell "sesh connect \"$(
  sesh list --icons | fzf-tmux -p 80%,70% \
    --no-sort --ansi --border-label ' sesh ' --prompt '⚡  ' \
    --header '  ^a all ^t tmux ^g configs ^x zoxide ^d tmux kill ^f find' \
    --bind 'tab:down,btab:up' \
    --bind 'ctrl-a:change-prompt(⚡  )+reload(sesh list --icons)' \
    --bind 'ctrl-t:change-prompt(🪟  )+reload(sesh list -t --icons)' \
    --bind 'ctrl-g:change-prompt(⚙️  )+reload(sesh list -c --icons)' \
    --bind 'ctrl-x:change-prompt(📁  )+reload(sesh list -z --icons)' \
    --bind 'ctrl-f:change-prompt(🔎  )+reload(fd -H -d 2 -t d -E .Trash . ~)' \
    --bind 'ctrl-d:execute(tmux kill-session -t {2..})+change-prompt(⚡  )+reload(sesh list --icons)' \
    --preview-window 'right:55%' \
    --preview 'sesh preview {}'
)\""

FZF_DEFAULT_OPTS=$FZF_DEFAULT_OPTS'
  --color=fg:#6e858c,fg+:#ffeded,bg:#181d1e,bg+:#262626
  --color=hl:#dadada,hl+:#5596ab,info:#606672,marker:#91d049
  --color=prompt:#809766,spinner:#af5fff,pointer:#a2b4d5,header:#87afaf
  --color=gutter:#181d1e,border:#48573d,separator:#48573d,preview-border:#5c5a5a
  --color=label:#aeaeae,query:#d9d9d9
  --preview-window="border-rounded" --prompt="> " --marker=">" --pointer="◆"
  --separator="─" --scrollbar="│"'

TMUX_FZF_OPTIONS="-p -w 85% -h 75% -m"
TMUX_FZF_SESSION_FORMAT="#{session_last_attached} #{session_windows} windows"

# List of plugins
set -g @plugin 'tmux-plugins/tpm'

set -g @plugin 'tmux-plugins/tmux-sensible'

set -g @plugin 'tmux-plugins/tmux-resurrect'
set -g @resurrect-strategy-nvim 'session'

set -g @plugin 'sainnhe/tmux-fzf'

set -g @plugin 'o0th/tmux-nova'

bind-key x kill-pane # skip "kill-pane 1? (y/n)" prompt
set -g detach-on-destroy off  # don't exit from tmux when closing a session

# Proper colors
set-option -sa terminal-features ',alacritty:RGB'

# Undercurl
set-option -g default-terminal "tmux-256color"
set-option -ga terminal-features ",alacritty:usstyle"

bind r source-file ~/.tmux.conf \; display-message "Config reloaded!"
bind v copy-mode
bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R

bind y switch-client -l

bind-key "n" run-shell -b "tmux switch-client -t Notes"

bind-key "T" run-shell -b "~/.tmux/plugins/tmux-fzf/scripts/session.sh switch"
# bind-key "T" run-shell -b "~/.tmux/plugins/tmux-fzf/scripts/session.sh"

# Plugin Config
set -g @resurrect-capture-pane-contents 'on'
run -b 'sleep 1 && ~/.tmux/plugins/tmux-resurrect/scripts/restore.sh'

set -g @nova-nerdfonts true
# set -g @nova-nerdfonts-left 
# set -g @nova-nerdfonts-right 

set-option -g status-position top

set -g @nova-pane-active-border-style "#44475a"
set -g @nova-pane-border-style "#282a36"
set -g @nova-status-style-bg "#141b1e"
set -g @nova-status-style-fg "#d8dee9"
set -g @nova-status-style-active-bg "#8ccf7e"
set -g @nova-status-style-active-fg "#232a2d"
set -g @nova-status-style-double-bg "#232a2d"

set -g @nova-pane "#I#{?pane_in_mode,  #{pane_mode},}  #W"

set -g @nova-segment-mode "#{?client_prefix,Ω,ω}"
set -g @nova-segment-mode-colors "#8ccf7e #2e3440"

set -g @nova-segment-session "#S "
set -g @nove-segment-session-colors "#8ccf7e #2e3440"

set -g @nova-segment-whoami "#(whoami)@#h"
set -g @nova-segment-whoami-colors "#8ccf7e #2e3440"

set -g @nova-rows 0
set -g @nova-segments-0-left "mode session"
set -g @nova-segments-0-right "path whoami"

set -g @nova-segment-path "#(echo #{pane_current_path} | sed 's#$HOME#~#;s#.*/.*/\\(.*/.*/\\?\\)#../\\1#')"
# Initialize TMUX plugin manager (keep this line at the very bottom of tmux.conf)
run '~/.tmux/plugins/tpm/tpm'

