set -g mouse on     #For tmux version 2.1 and up

set-window-option -g mode-keys vi
# Start windows and panes at 1, not 0
set -g base-index 1
setw -g pane-base-index 1
set-option -g update-environment "PATH" 
set-option -g prefix C-b
bind-key C-b send-prefix

FZF_DEFAULT_OPTS='
  --color fg:#5d6466,bg:#1e2527
  --color bg+:#ef7d7d,fg+:#2c2f30
  --color hl:#dadada,hl+:#26292a,gutter:#1e2527
  --color pointer:#373d49,info:#606672
  --border
  --color border:#1e2527
  --height 13
  --marker=">" --pointer="◆" --separator="─" --scrollbar="│"'

TMUX_FZF_OPTIONS="-p -w 85% -h 75% -m"
TMUX_FZF_SESSION_FORMAT="#{session_last_attached} #{session_windows} windows"

# List of plugins
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'tmux-plugins/tmux-resurrect'
set -g @plugin 'tmux-plugins/tmux-continuum'
set -g @plugin 'sainnhe/tmux-fzf'
set -g @plugin 'jonmosco/kube-tmux'
set -g @plugin 'erikw/tmux-powerline'
bind-key x kill-pane # skip "kill-pane 1? (y/n)" prompt
set -g detach-on-destroy off  # don't exit from tmux when closing a session

# Proper colors
set-option -sa terminal-features ',alacritty:RGB'

# Undercurl
set-option -g default-terminal "tmux-256color"
set-option -ga terminal-features ",alacritty:usstyle"

set-option -g status-position top

bind r source-file ~/.tmux.conf \; display-message "Config reloaded!"
bind v copy-mode
bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R

bind y switch-client -l

bind-key "g" run-shell -b "~/.tmux/scripts/timew.sh"

bind-key "n" run-shell -b "tmux switch-client -t Notes"

bind-key "t" run-shell -b "~/.tmux/plugins/tmux-fzf/scripts/session.sh switch"
bind-key "T" run-shell -b "~/.tmux/plugins/tmux-fzf/scripts/session.sh"

# Plugin Config
set -g @resurrect-capture-pane-contents 'on'
set -g @continuum-restore 'on'
# Initialize TMUX plugin manager (keep this line at the very bottom of tmux.conf)
run '~/.tmux/plugins/tpm/tpm'

